language: node_js
node_js:
  - "6.9.5"
before_script:
  - npm install
notifications:
  email:
    recipients:
      - GeoMass2000@gmail.com
    on_success: never # default: change
    on_failure: always # default: always